version: '3.4'

services:
  fastapi:
    image: fastapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER={}
      - POSTGRES_PASSWORD={}
      - POSTGRES_DB={}
      - POSTGRES_SERVER={}
      - POSTGRES_PORT={}



